"use client";

import GlobalLoader from "@/components/Loader";
import { useState } from "react";

export default function GenerateDataComponent() {
  const [loading, setLoading] = useState(false);
  const handleLoadHotels = async () => {
    setLoading(true);
    try {
      const response = await fetch("/api/hotelAPi/load-hotels");
      const data = await response.json();
      console.log(data);
    } catch (err: any) {
      console.log("Error occured in hotels load", err.message);
    } finally {
      setLoading(false);
    }
  };
  const handleLoadProperties = async () => {
    try {
      const response = await fetch("/api/gateway-casas/load-properties");
      console.log(response);
    } catch (err: any) {
      console.log(err.message);
    }
  };

  return (
    <>
      {/* <Layout headerStyle={1} footerStyle={1}> */}
      <main className="main">
        <GlobalLoader
          visible={loading}
          variant="pulse"
          size="lg"
          message="loading..."
          color="#4f46e5" // indigo-600
        />
        <section className="box-section box-location-shop box-location-shop-2 background-body">
          <div className="container d-flex gap-2">
            <div className="d-inline-block">
              {" "}
              <button
                className="btn btn-black-lg-square"
                onClick={handleLoadHotels}
                disabled={loading}
              >
                Load Hotels
              </button>
            </div>
            <div className="d-inline-block">
              {" "}
              <button
                className="btn btn-black-lg-square"
                onClick={handleLoadProperties}
              >
                Load Properties
              </button>
            </div>
          </div>
        </section>
      </main>

      {/* </Layout> */}
    </>
  );
}

const hotelDetails = {
  code: 19387,
  name: {
    content: "Blue Tree Premium Paulista",
  },
  description: {
    content:
      "Blue Tree Premium Paulista is centrally located in São Paulo just 12 km from Congonhas Airport and 30 km from Guarulhos Airport. This hotel is ideal for business and leisure travelers. Rooms are elegantly designed, with modern amenities and functional spaces. The hotel has rooms that are equipped with modern conference technology, which is sure to impress, and leisure facilities to ensure a comfortable stay for all types of travellers. \nHotel charges R$6. 00/day tourist tax. \n\nWe are making improvements to some areas of the hotel, including the lobby and common areas, and access to certain areas may be temporarily restricted, but alternatives will be made available. Our services and support will continue to operate normally. \nSauna temporarily disabled. ",
  },
  countryCode: "BR",
  stateCode: "SP",
  destinationCode: "SAO",
  zoneCode: 1,
  coordinates: {
    longitude: -46.655971,
    latitude: -23.560238,
  },
  categoryCode: "4EST",
  categoryGroupCode: "GRUPO4",
  chainCode: "BLUET",
  accommodationTypeCode: "H",
  boardCodes: ["BB", "AI", "HB", "FB", "RO", "DB", "CB"],
  segmentCodes: [34],
  address: {
    content: "Rua Peixoto Gomide 707",
    street: "Rua Peixoto Gomide 707",
  },
  postalCode: "01409-001",
  city: {
    content: "SAO PAULO",
  },
  email: "reservas@bluetree.com.br",
  giataCode: 54987,
  phones: [
    {
      phoneNumber: "+551101409001",
      phoneType: "PHONEBOOKING",
    },
    {
      phoneNumber: "+551101409001",
      phoneType: "PHONEHOTEL",
    },
    {
      phoneNumber: "+551131477000",
      phoneType: "FAXNUMBER",
    },
  ],
  rooms: [
    {
      roomCode: "BED.ST",
      isParentRoom: false,
      minPax: 1,
      maxPax: 1,
      maxAdults: 1,
      maxChildren: 0,
      minAdults: 1,
      roomType: "BED",
      characteristicCode: "ST",
    },
    {
      roomCode: "DBL.DB-SU",
      isParentRoom: true,
      minPax: 1,
      maxPax: 3,
      maxAdults: 2,
      maxChildren: 1,
      minAdults: 1,
      roomType: "DBL",
      characteristicCode: "DB-SU",
      roomFacilities: [
        {
          facilityCode: 100,
          facilityGroupCode: 60,
          indLogic: false,
          indFee: false,
          voucher: false,
        },
        {
          facilityCode: 220,
          facilityGroupCode: 60,
          indLogic: false,
          number: 0,
          voucher: false,
        },
        {
          facilityCode: 250,
          facilityGroupCode: 60,
          indYesOrNo: true,
          voucher: false,
        },
        {
          facilityCode: 261,
          facilityGroupCode: 60,
          indFee: false,
          indYesOrNo: true,
          voucher: false,
        },
        {
          facilityCode: 295,
          facilityGroupCode: 60,
          number: 28,
          indYesOrNo: true,
          voucher: false,
        },
        {
          facilityCode: 298,
          facilityGroupCode: 60,
          indLogic: false,
          number: 1,
          voucher: false,
        },
      ],
      roomStays: [
        {
          stayType: "BED",
          order: "1",
          description: "Bed room",
          roomStayFacilities: [
            {
              facilityCode: 150,
              facilityGroupCode: 61,
              number: 1,
            },
          ],
        },
      ],
      PMSRoomCode: "5179",
    },
    {
      roomCode: "DBL.DX",
      isParentRoom: true,
      minPax: 1,
      maxPax: 4,
      maxAdults: 4,
      maxChildren: 3,
      minAdults: 1,
      roomType: "DBL",
      characteristicCode: "DX",
      roomFacilities: [
        {
          facilityCode: 100,
          facilityGroupCode: 60,
          indLogic: false,
          indFee: false,
          voucher: false,
        },
        {
          facilityCode: 220,
          facilityGroupCode: 60,
          indLogic: false,
          number: 0,
          voucher: false,
        },
        {
          facilityCode: 250,
          facilityGroupCode: 60,
          indYesOrNo: true,
          voucher: false,
        },
        {
          facilityCode: 298,
          facilityGroupCode: 60,
          indLogic: true,
          number: 1,
          voucher: false,
        },
      ],
      roomStays: [
        {
          stayType: "BED",
          order: "1",
          description: "Bed room",
          roomStayFacilities: [
            {
              facilityCode: 294,
              facilityGroupCode: 61,
              number: 1,
            },
          ],
        },
      ],
      PMSRoomCode: "2946",
    },
    {
      roomCode: "DBL.DX-1",
      isParentRoom: true,
      minPax: 1,
      maxPax: 4,
      maxAdults: 4,
      maxChildren: 3,
      minAdults: 1,
      roomType: "DBL",
      characteristicCode: "DX-1",
      roomFacilities: [
        {
          facilityCode: 100,
          facilityGroupCode: 60,
          indLogic: false,
          indFee: false,
          voucher: false,
        },
        {
          facilityCode: 220,
          facilityGroupCode: 60,
          indLogic: false,
          voucher: false,
        },
        {
          facilityCode: 250,
          facilityGroupCode: 60,
          indYesOrNo: true,
          voucher: false,
        },
        {
          facilityCode: 298,
          facilityGroupCode: 60,
          indLogic: false,
          number: 1,
          voucher: false,
        },
      ],
      roomStays: [
        {
          stayType: "BED",
          order: "1",
          description: "Bed room",
        },
      ],
      PMSRoomCode: "2946",
    },
    {
      roomCode: "DBL.DX-2",
      isParentRoom: true,
      minPax: 1,
      maxPax: 4,
      maxAdults: 4,
      maxChildren: 3,
      minAdults: 1,
      roomType: "DBL",
      characteristicCode: "DX-2",
      roomFacilities: [
        {
          facilityCode: 100,
          facilityGroupCode: 60,
          indLogic: false,
          indFee: false,
          voucher: false,
        },
        {
          facilityCode: 220,
          facilityGroupCode: 60,
          indLogic: false,
          voucher: false,
        },
        {
          facilityCode: 250,
          facilityGroupCode: 60,
          indYesOrNo: true,
          voucher: false,
        },
        {
          facilityCode: 298,
          facilityGroupCode: 60,
          indLogic: false,
          number: 1,
          voucher: false,
        },
      ],
      roomStays: [
        {
          stayType: "BED",
          order: "1",
          description: "Bed room",
        },
      ],
      PMSRoomCode: "2946",
    },
    {
      roomCode: "DBL.DX-3",
      isParentRoom: true,
      minPax: 1,
      maxPax: 4,
      maxAdults: 4,
      maxChildren: 3,
      minAdults: 1,
      roomType: "DBL",
      characteristicCode: "DX-3",
      roomFacilities: [
        {
          facilityCode: 100,
          facilityGroupCode: 60,
          indLogic: false,
          indFee: false,
          voucher: false,
        },
        {
          facilityCode: 220,
          facilityGroupCode: 60,
          indLogic: false,
          voucher: false,
        },
        {
          facilityCode: 250,
          facilityGroupCode: 60,
          indYesOrNo: true,
          voucher: false,
        },
        {
          facilityCode: 298,
          facilityGroupCode: 60,
          indLogic: false,
          number: 1,
          voucher: false,
        },
      ],
      roomStays: [
        {
          stayType: "BED",
          order: "1",
          description: "Bed room",
        },
      ],
      PMSRoomCode: "2946",
    },
    {
      roomCode: "DBL.DX-4",
      isParentRoom: true,
      minPax: 1,
      maxPax: 4,
      maxAdults: 4,
      maxChildren: 3,
      minAdults: 1,
      roomType: "DBL",
      characteristicCode: "DX-4",
      roomFacilities: [
        {
          facilityCode: 100,
          facilityGroupCode: 60,
          indLogic: false,
          indFee: false,
          voucher: false,
        },
        {
          facilityCode: 220,
          facilityGroupCode: 60,
          indLogic: false,
          voucher: false,
        },
        {
          facilityCode: 250,
          facilityGroupCode: 60,
          indYesOrNo: true,
          voucher: false,
        },
        {
          facilityCode: 298,
          facilityGroupCode: 60,
          indLogic: false,
          number: 1,
          voucher: false,
        },
      ],
      roomStays: [
        {
          stayType: "BED",
          order: "1",
          description: "Bed room",
        },
      ],
      PMSRoomCode: "2976",
    },
    {
      roomCode: "DBL.DX-5",
      isParentRoom: true,
      minPax: 1,
      maxPax: 4,
      maxAdults: 4,
      maxChildren: 3,
      minAdults: 1,
      roomType: "DBL",
      characteristicCode: "DX-5",
      roomFacilities: [
        {
          facilityCode: 100,
          facilityGroupCode: 60,
          indLogic: false,
          indFee: false,
          voucher: false,
        },
        {
          facilityCode: 220,
          facilityGroupCode: 60,
          indLogic: false,
          voucher: false,
        },
        {
          facilityCode: 250,
          facilityGroupCode: 60,
          indYesOrNo: true,
          voucher: false,
        },
        {
          facilityCode: 298,
          facilityGroupCode: 60,
          indLogic: false,
          number: 1,
          voucher: false,
        },
      ],
      roomStays: [
        {
          stayType: "BED",
          order: "1",
          description: "Bed room",
        },
      ],
      PMSRoomCode: "2976",
    },
    {
      roomCode: "DBL.DX-6",
      isParentRoom: true,
      minPax: 1,
      maxPax: 4,
      maxAdults: 4,
      maxChildren: 3,
      minAdults: 1,
      roomType: "DBL",
      characteristicCode: "DX-6",
      roomFacilities: [
        {
          facilityCode: 100,
          facilityGroupCode: 60,
          indLogic: false,
          indFee: false,
          voucher: false,
        },
        {
          facilityCode: 220,
          facilityGroupCode: 60,
          indLogic: false,
          voucher: false,
        },
        {
          facilityCode: 250,
          facilityGroupCode: 60,
          indYesOrNo: true,
          voucher: false,
        },
        {
          facilityCode: 298,
          facilityGroupCode: 60,
          indLogic: false,
          number: 1,
          voucher: false,
        },
      ],
      roomStays: [
        {
          stayType: "BED",
          order: "1",
          description: "Bed room",
        },
      ],
      PMSRoomCode: "2976",
    },
    {
      roomCode: "DBL.DX-GD",
      isParentRoom: false,
      minPax: 1,
      maxPax: 4,
      maxAdults: 4,
      maxChildren: 3,
      minAdults: 1,
      roomType: "DBL",
      characteristicCode: "DX-GD",
    },
    {
      roomCode: "DBL.DX-PE",
      isParentRoom: true,
      minPax: 1,
      maxPax: 4,
      maxAdults: 4,
      maxChildren: 3,
      minAdults: 1,
      roomType: "DBL",
      characteristicCode: "DX-PE",
      roomFacilities: [
        {
          facilityCode: 100,
          facilityGroupCode: 60,
          indLogic: false,
          indFee: false,
          voucher: false,
        },
        {
          facilityCode: 220,
          facilityGroupCode: 60,
          indLogic: false,
          voucher: false,
        },
        {
          facilityCode: 250,
          facilityGroupCode: 60,
          indYesOrNo: true,
          voucher: false,
        },
        {
          facilityCode: 298,
          facilityGroupCode: 60,
          indLogic: false,
          number: 1,
          voucher: false,
        },
      ],
      roomStays: [
        {
          stayType: "BED",
          order: "1",
          description: "Bed room",
        },
      ],
      PMSRoomCode: "2976",
    },
    {
      roomCode: "DBL.DX-SU",
      isParentRoom: false,
      minPax: 1,
      maxPax: 4,
      maxAdults: 4,
      maxChildren: 3,
      minAdults: 1,
      roomType: "DBL",
      characteristicCode: "DX-SU",
    },
    {
      roomCode: "DBL.EY",
      isParentRoom: false,
      minPax: 1,
      maxPax: 4,
      maxAdults: 4,
      maxChildren: 3,
      minAdults: 1,
      roomType: "DBL",
      characteristicCode: "EY",
    },
    {
      roomCode: "DBL.GD-SU",
      isParentRoom: false,
      minPax: 1,
      maxPax: 4,
      maxAdults: 4,
      maxChildren: 3,
      minAdults: 1,
      roomType: "DBL",
      characteristicCode: "GD-SU",
    },
    {
      roomCode: "DBL.LX",
      isParentRoom: true,
      minPax: 1,
      maxPax: 3,
      maxAdults: 2,
      maxChildren: 1,
      minAdults: 1,
      roomType: "DBL",
      characteristicCode: "LX",
      roomFacilities: [
        {
          facilityCode: 100,
          facilityGroupCode: 60,
          indLogic: false,
          indFee: false,
          voucher: false,
        },
        {
          facilityCode: 220,
          facilityGroupCode: 60,
          indLogic: false,
          number: 0,
          voucher: false,
        },
        {
          facilityCode: 250,
          facilityGroupCode: 60,
          indYesOrNo: true,
          voucher: false,
        },
        {
          facilityCode: 261,
          facilityGroupCode: 60,
          indFee: false,
          indYesOrNo: true,
          voucher: false,
        },
        {
          facilityCode: 295,
          facilityGroupCode: 60,
          number: 28,
          indYesOrNo: true,
          voucher: false,
        },
        {
          facilityCode: 298,
          facilityGroupCode: 60,
          indLogic: false,
          number: 1,
          voucher: false,
        },
      ],
      roomStays: [
        {
          stayType: "BED",
          order: "1",
          description: "Bed room",
          roomStayFacilities: [
            {
              facilityCode: 150,
              facilityGroupCode: 61,
              number: 1,
            },
          ],
        },
      ],
      PMSRoomCode: "10",
    },
    {
      roomCode: "DBL.LX-1",
      isParentRoom: false,
      minPax: 1,
      maxPax: 4,
      maxAdults: 4,
      maxChildren: 3,
      minAdults: 1,
      roomType: "DBL",
      characteristicCode: "LX-1",
    },
    {
      roomCode: "DBL.PE",
      isParentRoom: true,
      minPax: 1,
      maxPax: 3,
      maxAdults: 2,
      maxChildren: 1,
      minAdults: 1,
      roomType: "DBL",
      characteristicCode: "PE",
      roomFacilities: [
        {
          facilityCode: 100,
          facilityGroupCode: 60,
          indLogic: false,
          indFee: false,
          voucher: false,
        },
        {
          facilityCode: 220,
          facilityGroupCode: 60,
          indLogic: false,
          number: 0,
          voucher: false,
        },
        {
          facilityCode: 250,
          facilityGroupCode: 60,
          indYesOrNo: true,
          voucher: false,
        },
        {
          facilityCode: 261,
          facilityGroupCode: 60,
          indFee: false,
          indYesOrNo: true,
          voucher: false,
        },
        {
          facilityCode: 295,
          facilityGroupCode: 60,
          number: 28,
          indYesOrNo: true,
          voucher: false,
        },
        {
          facilityCode: 298,
          facilityGroupCode: 60,
          indLogic: false,
          number: 1,
          voucher: false,
        },
      ],
      roomStays: [
        {
          stayType: "BED",
          order: "1",
          description: "Bed room",
          roomStayFacilities: [
            {
              facilityCode: 150,
              facilityGroupCode: 61,
              number: 1,
            },
          ],
        },
      ],
      PMSRoomCode: "294",
    },
    {
      roomCode: "DBL.PE-1",
      isParentRoom: false,
      minPax: 1,
      maxPax: 4,
      maxAdults: 4,
      maxChildren: 3,
      minAdults: 1,
      roomType: "DBL",
      characteristicCode: "PE-1",
    },
    {
      roomCode: "DBL.QN",
      isParentRoom: false,
      minPax: 1,
      maxPax: 4,
      maxAdults: 4,
      maxChildren: 3,
      minAdults: 1,
      roomType: "DBL",
      characteristicCode: "QN",
    },
    {
      roomCode: "DBL.QN-SU",
      isParentRoom: false,
      minPax: 1,
      maxPax: 4,
      maxAdults: 4,
      maxChildren: 3,
      minAdults: 1,
      roomType: "DBL",
      characteristicCode: "QN-SU",
    },
    {
      roomCode: "DBL.ST",
      isParentRoom: false,
      minPax: 1,
      maxPax: 4,
      maxAdults: 4,
      maxChildren: 3,
      minAdults: 1,
      roomType: "DBL",
      characteristicCode: "ST",
    },
    {
      roomCode: "DBL.SU",
      isParentRoom: false,
      minPax: 1,
      maxPax: 3,
      maxAdults: 2,
      maxChildren: 1,
      minAdults: 1,
      roomType: "DBL",
      characteristicCode: "SU",
      roomFacilities: [
        {
          facilityCode: 10,
          facilityGroupCode: 60,
          indLogic: true,
          number: 1,
          voucher: false,
        },
        {
          facilityCode: 50,
          facilityGroupCode: 60,
          indLogic: true,
          indFee: false,
          voucher: false,
        },
        {
          facilityCode: 80,
          facilityGroupCode: 60,
          indLogic: true,
          indFee: false,
          voucher: false,
        },
        {
          facilityCode: 100,
          facilityGroupCode: 60,
          indLogic: true,
          indFee: false,
          voucher: false,
        },
        {
          facilityCode: 160,
          facilityGroupCode: 60,
          indLogic: true,
          indFee: false,
          voucher: false,
        },
        {
          facilityCode: 170,
          facilityGroupCode: 60,
          indLogic: true,
          voucher: false,
        },
        {
          facilityCode: 190,
          facilityGroupCode: 60,
          indLogic: true,
          indFee: false,
          voucher: false,
        },
        {
          facilityCode: 195,
          facilityGroupCode: 60,
          indLogic: true,
          indFee: false,
          voucher: false,
        },
        {
          facilityCode: 220,
          facilityGroupCode: 60,
          indLogic: false,
          number: 0,
          voucher: false,
        },
        {
          facilityCode: 250,
          facilityGroupCode: 60,
          indYesOrNo: false,
          voucher: false,
        },
        {
          facilityCode: 261,
          facilityGroupCode: 60,
          indFee: false,
          indYesOrNo: true,
          voucher: false,
        },
        {
          facilityCode: 295,
          facilityGroupCode: 60,
          number: 28,
          indYesOrNo: true,
          voucher: false,
        },
        {
          facilityCode: 298,
          facilityGroupCode: 60,
          indLogic: false,
          number: 1,
          voucher: false,
        },
      ],
      roomStays: [
        {
          stayType: "BED",
          order: "1",
          description: "Bed room",
          roomStayFacilities: [
            {
              facilityCode: 150,
              facilityGroupCode: 61,
              number: 1,
            },
          ],
        },
      ],
      PMSRoomCode: "4",
    },
    {
      roomCode: "DBL.SU-1",
      isParentRoom: true,
      minPax: 1,
      maxPax: 4,
      maxAdults: 4,
      maxChildren: 3,
      minAdults: 1,
      roomType: "DBL",
      characteristicCode: "SU-1",
      roomFacilities: [
        {
          facilityCode: 100,
          facilityGroupCode: 60,
          indLogic: false,
          indFee: false,
          voucher: false,
        },
        {
          facilityCode: 220,
          facilityGroupCode: 60,
          indLogic: false,
          voucher: false,
        },
        {
          facilityCode: 250,
          facilityGroupCode: 60,
          indYesOrNo: true,
          voucher: false,
        },
        {
          facilityCode: 298,
          facilityGroupCode: 60,
          indLogic: false,
          number: 1,
          voucher: false,
        },
      ],
      roomStays: [
        {
          stayType: "BED",
          order: "1",
          description: "Bed room",
        },
      ],
      PMSRoomCode: "5179",
    },
    {
      roomCode: "DBL.SU-2",
      isParentRoom: true,
      minPax: 1,
      maxPax: 4,
      maxAdults: 4,
      maxChildren: 3,
      minAdults: 1,
      roomType: "DBL",
      characteristicCode: "SU-2",
      roomFacilities: [
        {
          facilityCode: 100,
          facilityGroupCode: 60,
          indLogic: false,
          indFee: false,
          voucher: false,
        },
        {
          facilityCode: 220,
          facilityGroupCode: 60,
          indLogic: false,
          voucher: false,
        },
        {
          facilityCode: 250,
          facilityGroupCode: 60,
          indYesOrNo: true,
          voucher: false,
        },
        {
          facilityCode: 298,
          facilityGroupCode: 60,
          indLogic: false,
          number: 1,
          voucher: false,
        },
      ],
      roomStays: [
        {
          stayType: "BED",
          order: "1",
          description: "Bed room",
        },
      ],
      PMSRoomCode: "5179",
    },
    {
      roomCode: "DBL.SU-3",
      isParentRoom: false,
      minPax: 1,
      maxPax: 4,
      maxAdults: 4,
      maxChildren: 3,
      minAdults: 1,
      roomType: "DBL",
      characteristicCode: "SU-3",
    },
    {
      roomCode: "DBL.PI",
      isParentRoom: false,
      minPax: 1,
      maxPax: 4,
      maxAdults: 4,
      maxChildren: 3,
      minAdults: 1,
      roomType: "DBL",
      characteristicCode: "PI",
    },
    {
      roomCode: "DBT.DX-PE",
      isParentRoom: false,
      minPax: 1,
      maxPax: 6,
      maxAdults: 6,
      maxChildren: 3,
      minAdults: 1,
      roomType: "DBT",
      characteristicCode: "DX-PE",
    },
    {
      roomCode: "DBT.DX-SU",
      isParentRoom: false,
      minPax: 1,
      maxPax: 6,
      maxAdults: 6,
      maxChildren: 3,
      minAdults: 1,
      roomType: "DBT",
      characteristicCode: "DX-SU",
    },
    {
      roomCode: "DBT.ST",
      isParentRoom: false,
      minPax: 1,
      maxPax: 6,
      maxAdults: 6,
      maxChildren: 3,
      minAdults: 1,
      roomType: "DBT",
      characteristicCode: "ST",
    },
    {
      roomCode: "DBT.SU",
      isParentRoom: false,
      minPax: 1,
      maxPax: 6,
      maxAdults: 6,
      maxChildren: 3,
      minAdults: 1,
      roomType: "DBT",
      characteristicCode: "SU",
    },
    {
      roomCode: "DBT.PI",
      isParentRoom: false,
      minPax: 1,
      maxPax: 6,
      maxAdults: 6,
      maxChildren: 3,
      minAdults: 1,
      roomType: "DBT",
      characteristicCode: "PI",
    },
    {
      roomCode: "DUS.DX",
      isParentRoom: false,
      minPax: 1,
      maxPax: 2,
      maxAdults: 1,
      maxChildren: 1,
      minAdults: 1,
      roomType: "DUS",
      characteristicCode: "DX",
    },
    {
      roomCode: "DUS.SU",
      isParentRoom: false,
      minPax: 1,
      maxPax: 2,
      maxAdults: 1,
      maxChildren: 1,
      minAdults: 1,
      roomType: "DUS",
      characteristicCode: "SU",
    },
    {
      roomCode: "ROO.DX-PI",
      isParentRoom: false,
      minPax: 1,
      maxPax: 10,
      maxAdults: 10,
      maxChildren: 6,
      minAdults: 1,
      roomType: "ROO",
      characteristicCode: "DX-PI",
    },
    {
      roomCode: "ROO.RO",
      isParentRoom: false,
      minPax: 1,
      maxPax: 10,
      maxAdults: 10,
      maxChildren: 6,
      minAdults: 1,
      roomType: "ROO",
      characteristicCode: "RO",
    },
    {
      roomCode: "ROO.ST",
      isParentRoom: false,
      minPax: 1,
      maxPax: 10,
      maxAdults: 10,
      maxChildren: 6,
      minAdults: 1,
      roomType: "ROO",
      characteristicCode: "ST",
    },
    {
      roomCode: "ROO.SU",
      isParentRoom: false,
      minPax: 1,
      maxPax: 10,
      maxAdults: 10,
      maxChildren: 6,
      minAdults: 1,
      roomType: "ROO",
      characteristicCode: "SU",
    },
    {
      roomCode: "ROO.PI",
      isParentRoom: false,
      minPax: 1,
      maxPax: 10,
      maxAdults: 10,
      maxChildren: 6,
      minAdults: 1,
      roomType: "ROO",
      characteristicCode: "PI",
    },
    {
      roomCode: "SGL.2B-1",
      isParentRoom: true,
      minPax: 1,
      maxPax: 1,
      maxAdults: 1,
      maxChildren: 0,
      minAdults: 1,
      roomType: "SGL",
      characteristicCode: "2B-1",
      roomFacilities: [
        {
          facilityCode: 100,
          facilityGroupCode: 60,
          indLogic: false,
          indFee: false,
          voucher: false,
        },
        {
          facilityCode: 220,
          facilityGroupCode: 60,
          indLogic: false,
          number: 0,
          voucher: false,
        },
        {
          facilityCode: 250,
          facilityGroupCode: 60,
          indYesOrNo: true,
          voucher: false,
        },
        {
          facilityCode: 298,
          facilityGroupCode: 60,
          indLogic: false,
          number: 1,
          voucher: false,
        },
      ],
      roomStays: [
        {
          stayType: "BED",
          order: "1",
          description: "Bed room",
        },
      ],
      PMSRoomCode: "2945",
    },
    {
      roomCode: "SGL.2B-2",
      isParentRoom: true,
      minPax: 1,
      maxPax: 1,
      maxAdults: 1,
      maxChildren: 0,
      minAdults: 1,
      roomType: "SGL",
      characteristicCode: "2B-2",
      roomFacilities: [
        {
          facilityCode: 100,
          facilityGroupCode: 60,
          indLogic: false,
          indFee: false,
          voucher: false,
        },
        {
          facilityCode: 220,
          facilityGroupCode: 60,
          indLogic: false,
          number: 0,
          voucher: false,
        },
        {
          facilityCode: 250,
          facilityGroupCode: 60,
          indYesOrNo: true,
          voucher: false,
        },
        {
          facilityCode: 298,
          facilityGroupCode: 60,
          indLogic: false,
          number: 1,
          voucher: false,
        },
      ],
      roomStays: [
        {
          stayType: "BED",
          order: "1",
          description: "Bed room",
        },
      ],
      PMSRoomCode: "2945",
    },
    {
      roomCode: "SGL.DX",
      isParentRoom: true,
      minPax: 1,
      maxPax: 1,
      maxAdults: 1,
      maxChildren: 0,
      minAdults: 1,
      roomType: "SGL",
      characteristicCode: "DX",
      roomFacilities: [
        {
          facilityCode: 100,
          facilityGroupCode: 60,
          indLogic: false,
          indFee: false,
          voucher: false,
        },
        {
          facilityCode: 220,
          facilityGroupCode: 60,
          indLogic: false,
          number: 0,
          voucher: false,
        },
        {
          facilityCode: 250,
          facilityGroupCode: 60,
          indYesOrNo: true,
          voucher: false,
        },
        {
          facilityCode: 298,
          facilityGroupCode: 60,
          indLogic: true,
          number: 1,
          voucher: false,
        },
      ],
      roomStays: [
        {
          stayType: "BED",
          order: "1",
          description: "Bed room",
          roomStayFacilities: [
            {
              facilityCode: 1,
              facilityGroupCode: 61,
              number: 2,
            },
          ],
        },
      ],
      PMSRoomCode: "5180",
    },
    {
      roomCode: "SGL.DX-1",
      isParentRoom: true,
      minPax: 1,
      maxPax: 1,
      maxAdults: 1,
      maxChildren: 0,
      minAdults: 1,
      roomType: "SGL",
      characteristicCode: "DX-1",
      roomFacilities: [
        {
          facilityCode: 100,
          facilityGroupCode: 60,
          indLogic: false,
          indFee: false,
          voucher: false,
        },
        {
          facilityCode: 220,
          facilityGroupCode: 60,
          indLogic: false,
          voucher: false,
        },
        {
          facilityCode: 250,
          facilityGroupCode: 60,
          indYesOrNo: true,
          voucher: false,
        },
        {
          facilityCode: 298,
          facilityGroupCode: 60,
          indLogic: false,
          number: 1,
          voucher: false,
        },
      ],
      roomStays: [
        {
          stayType: "BED",
          order: "1",
          description: "Bed room",
        },
      ],
      PMSRoomCode: "5180",
    },
    {
      roomCode: "SGL.DX-2",
      isParentRoom: true,
      minPax: 1,
      maxPax: 1,
      maxAdults: 1,
      maxChildren: 0,
      minAdults: 1,
      roomType: "SGL",
      characteristicCode: "DX-2",
      roomFacilities: [
        {
          facilityCode: 100,
          facilityGroupCode: 60,
          indLogic: false,
          indFee: false,
          voucher: false,
        },
        {
          facilityCode: 220,
          facilityGroupCode: 60,
          indLogic: false,
          voucher: false,
        },
        {
          facilityCode: 250,
          facilityGroupCode: 60,
          indYesOrNo: true,
          voucher: false,
        },
        {
          facilityCode: 298,
          facilityGroupCode: 60,
          indLogic: false,
          number: 1,
          voucher: false,
        },
      ],
      roomStays: [
        {
          stayType: "BED",
          order: "1",
          description: "Bed room",
        },
      ],
      PMSRoomCode: "5180",
    },
    {
      roomCode: "SGL.DX-PE",
      isParentRoom: true,
      minPax: 1,
      maxPax: 1,
      maxAdults: 1,
      maxChildren: 0,
      minAdults: 1,
      roomType: "SGL",
      characteristicCode: "DX-PE",
      roomFacilities: [
        {
          facilityCode: 100,
          facilityGroupCode: 60,
          indLogic: false,
          indFee: false,
          voucher: false,
        },
        {
          facilityCode: 220,
          facilityGroupCode: 60,
          indLogic: false,
          voucher: false,
        },
        {
          facilityCode: 250,
          facilityGroupCode: 60,
          indYesOrNo: true,
          voucher: false,
        },
        {
          facilityCode: 298,
          facilityGroupCode: 60,
          indLogic: false,
          number: 1,
          voucher: false,
        },
      ],
      roomStays: [
        {
          stayType: "BED",
          order: "1",
          description: "Bed room",
        },
      ],
      PMSRoomCode: "27956",
    },
    {
      roomCode: "SGL.LX",
      isParentRoom: true,
      minPax: 1,
      maxPax: 1,
      maxAdults: 1,
      maxChildren: 0,
      minAdults: 1,
      roomType: "SGL",
      characteristicCode: "LX",
      roomFacilities: [
        {
          facilityCode: 100,
          facilityGroupCode: 60,
          indLogic: false,
          indFee: false,
          voucher: false,
        },
        {
          facilityCode: 220,
          facilityGroupCode: 60,
          indLogic: false,
          number: 0,
          voucher: false,
        },
        {
          facilityCode: 250,
          facilityGroupCode: 60,
          indYesOrNo: true,
          voucher: false,
        },
        {
          facilityCode: 261,
          facilityGroupCode: 60,
          indFee: false,
          indYesOrNo: false,
          voucher: false,
        },
        {
          facilityCode: 295,
          facilityGroupCode: 60,
          number: 28,
          indYesOrNo: true,
          voucher: false,
        },
        {
          facilityCode: 298,
          facilityGroupCode: 60,
          indLogic: false,
          number: 1,
          voucher: false,
        },
      ],
      roomStays: [
        {
          stayType: "BED",
          order: "1",
          description: "Bed room",
          roomStayFacilities: [
            {
              facilityCode: 150,
              facilityGroupCode: 61,
              number: 1,
            },
          ],
        },
      ],
      PMSRoomCode: "12",
    },
    {
      roomCode: "SGL.LX-1",
      isParentRoom: true,
      minPax: 1,
      maxPax: 1,
      maxAdults: 1,
      maxChildren: 0,
      minAdults: 1,
      roomType: "SGL",
      characteristicCode: "LX-1",
      roomFacilities: [
        {
          facilityCode: 100,
          facilityGroupCode: 60,
          indLogic: false,
          indFee: false,
          voucher: false,
        },
        {
          facilityCode: 220,
          facilityGroupCode: 60,
          indLogic: false,
          voucher: false,
        },
        {
          facilityCode: 250,
          facilityGroupCode: 60,
          indYesOrNo: true,
          voucher: false,
        },
        {
          facilityCode: 298,
          facilityGroupCode: 60,
          indLogic: false,
          number: 1,
          voucher: false,
        },
      ],
      roomStays: [
        {
          stayType: "BED",
          order: "1",
          description: "Bed room",
        },
      ],
      PMSRoomCode: "27956",
    },
    {
      roomCode: "SGL.LX-2",
      isParentRoom: true,
      minPax: 1,
      maxPax: 1,
      maxAdults: 1,
      maxChildren: 0,
      minAdults: 1,
      roomType: "SGL",
      characteristicCode: "LX-2",
      roomFacilities: [
        {
          facilityCode: 100,
          facilityGroupCode: 60,
          indLogic: false,
          indFee: false,
          voucher: false,
        },
        {
          facilityCode: 220,
          facilityGroupCode: 60,
          indLogic: false,
          voucher: false,
        },
        {
          facilityCode: 250,
          facilityGroupCode: 60,
          indYesOrNo: true,
          voucher: false,
        },
        {
          facilityCode: 298,
          facilityGroupCode: 60,
          indLogic: false,
          number: 1,
          voucher: false,
        },
      ],
      roomStays: [
        {
          stayType: "BED",
          order: "1",
          description: "Bed room",
        },
      ],
      PMSRoomCode: "27956",
    },
    {
      roomCode: "SGL.PE",
      isParentRoom: false,
      minPax: 1,
      maxPax: 1,
      maxAdults: 1,
      maxChildren: 0,
      minAdults: 1,
      roomType: "SGL",
      characteristicCode: "PE",
      roomFacilities: [
        {
          facilityCode: 220,
          facilityGroupCode: 60,
          indLogic: false,
          number: 0,
          voucher: false,
        },
        {
          facilityCode: 250,
          facilityGroupCode: 60,
          indYesOrNo: false,
          voucher: false,
        },
        {
          facilityCode: 261,
          facilityGroupCode: 60,
          indFee: false,
          indYesOrNo: true,
          voucher: false,
        },
        {
          facilityCode: 295,
          facilityGroupCode: 60,
          number: 28,
          indYesOrNo: true,
          voucher: false,
        },
      ],
      roomStays: [
        {
          stayType: "BED",
          order: "1",
          description: "Bed room",
          roomStayFacilities: [
            {
              facilityCode: 1,
              facilityGroupCode: 61,
              number: 1,
            },
            {
              facilityCode: 150,
              facilityGroupCode: 61,
              number: 1,
            },
          ],
        },
      ],
      PMSRoomCode: "294",
    },
    {
      roomCode: "SGL.ST",
      isParentRoom: false,
      minPax: 1,
      maxPax: 1,
      maxAdults: 1,
      maxChildren: 0,
      minAdults: 1,
      roomType: "SGL",
      characteristicCode: "ST",
    },
    {
      roomCode: "SGL.SU",
      isParentRoom: false,
      minPax: 1,
      maxPax: 1,
      maxAdults: 1,
      maxChildren: 0,
      minAdults: 1,
      roomType: "SGL",
      characteristicCode: "SU",
      roomFacilities: [
        {
          facilityCode: 10,
          facilityGroupCode: 60,
          indLogic: true,
          number: 1,
          voucher: false,
        },
        {
          facilityCode: 50,
          facilityGroupCode: 60,
          indLogic: true,
          indFee: false,
          voucher: false,
        },
        {
          facilityCode: 80,
          facilityGroupCode: 60,
          indLogic: true,
          indFee: false,
          voucher: false,
        },
        {
          facilityCode: 100,
          facilityGroupCode: 60,
          indLogic: true,
          indFee: false,
          voucher: false,
        },
        {
          facilityCode: 160,
          facilityGroupCode: 60,
          indLogic: true,
          indFee: false,
          voucher: false,
        },
        {
          facilityCode: 170,
          facilityGroupCode: 60,
          indLogic: true,
          voucher: false,
        },
        {
          facilityCode: 190,
          facilityGroupCode: 60,
          indLogic: true,
          indFee: false,
          voucher: false,
        },
        {
          facilityCode: 195,
          facilityGroupCode: 60,
          indLogic: true,
          indFee: false,
          voucher: false,
        },
        {
          facilityCode: 220,
          facilityGroupCode: 60,
          indLogic: false,
          number: 0,
          voucher: false,
        },
        {
          facilityCode: 250,
          facilityGroupCode: 60,
          indYesOrNo: false,
          voucher: false,
        },
        {
          facilityCode: 261,
          facilityGroupCode: 60,
          indFee: false,
          indYesOrNo: true,
          voucher: false,
        },
        {
          facilityCode: 295,
          facilityGroupCode: 60,
          number: 28,
          indYesOrNo: true,
          voucher: false,
        },
        {
          facilityCode: 298,
          facilityGroupCode: 60,
          indLogic: false,
          number: 1,
          voucher: false,
        },
      ],
      roomStays: [
        {
          stayType: "BED",
          order: "1",
          description: "Bed room",
          roomStayFacilities: [
            {
              facilityCode: 150,
              facilityGroupCode: 61,
              number: 1,
            },
          ],
        },
      ],
      PMSRoomCode: "4",
    },
    {
      roomCode: "SGL.SU-1",
      isParentRoom: false,
      minPax: 1,
      maxPax: 1,
      maxAdults: 1,
      maxChildren: 0,
      minAdults: 1,
      roomType: "SGL",
      characteristicCode: "SU-1",
    },
    {
      roomCode: "SGL.2B",
      isParentRoom: true,
      minPax: 1,
      maxPax: 1,
      maxAdults: 1,
      maxChildren: 0,
      minAdults: 1,
      roomType: "SGL",
      characteristicCode: "2B",
      roomFacilities: [
        {
          facilityCode: 100,
          facilityGroupCode: 60,
          indLogic: false,
          indFee: false,
          voucher: false,
        },
        {
          facilityCode: 220,
          facilityGroupCode: 60,
          indLogic: false,
          voucher: false,
        },
        {
          facilityCode: 250,
          facilityGroupCode: 60,
          indYesOrNo: true,
          voucher: false,
        },
        {
          facilityCode: 298,
          facilityGroupCode: 60,
          indLogic: false,
          number: 1,
          voucher: false,
        },
      ],
      roomStays: [
        {
          stayType: "BED",
          order: "1",
          description: "Bed room",
        },
      ],
      PMSRoomCode: "2945",
    },
    {
      roomCode: "SGL.2B-DX",
      isParentRoom: true,
      minPax: 1,
      maxPax: 1,
      maxAdults: 1,
      maxChildren: 0,
      minAdults: 1,
      roomType: "SGL",
      characteristicCode: "2B-DX",
      roomFacilities: [
        {
          facilityCode: 100,
          facilityGroupCode: 60,
          indLogic: false,
          indFee: false,
          voucher: false,
        },
        {
          facilityCode: 220,
          facilityGroupCode: 60,
          indLogic: false,
          voucher: false,
        },
        {
          facilityCode: 250,
          facilityGroupCode: 60,
          indYesOrNo: true,
          voucher: false,
        },
        {
          facilityCode: 298,
          facilityGroupCode: 60,
          indLogic: false,
          number: 1,
          voucher: false,
        },
      ],
      roomStays: [
        {
          stayType: "BED",
          order: "1",
          description: "Bed room",
        },
      ],
      PMSRoomCode: "5180",
    },
    {
      roomCode: "STU.ST",
      isParentRoom: false,
      minPax: 1,
      maxPax: 5,
      maxAdults: 5,
      maxChildren: 3,
      minAdults: 1,
      roomType: "STU",
      characteristicCode: "ST",
    },
    {
      roomCode: "SUI.PI-1",
      isParentRoom: true,
      minPax: 1,
      maxPax: 8,
      maxAdults: 8,
      maxChildren: 5,
      minAdults: 1,
      roomType: "SUI",
      characteristicCode: "PI-1",
      roomFacilities: [
        {
          facilityCode: 100,
          facilityGroupCode: 60,
          indLogic: false,
          indFee: false,
          voucher: false,
        },
        {
          facilityCode: 220,
          facilityGroupCode: 60,
          indLogic: false,
          voucher: false,
        },
        {
          facilityCode: 250,
          facilityGroupCode: 60,
          indYesOrNo: true,
          voucher: false,
        },
        {
          facilityCode: 298,
          facilityGroupCode: 60,
          indLogic: false,
          number: 1,
          voucher: false,
        },
      ],
      roomStays: [
        {
          stayType: "BED",
          order: "1",
          description: "Bed room",
        },
      ],
      PMSRoomCode: "29369",
    },
    {
      roomCode: "SUI.ST",
      isParentRoom: false,
      minPax: 1,
      maxPax: 8,
      maxAdults: 8,
      maxChildren: 5,
      minAdults: 1,
      roomType: "SUI",
      characteristicCode: "ST",
    },
    {
      roomCode: "SUI.PI",
      isParentRoom: true,
      minPax: 1,
      maxPax: 8,
      maxAdults: 8,
      maxChildren: 5,
      minAdults: 1,
      roomType: "SUI",
      characteristicCode: "PI",
      roomFacilities: [
        {
          facilityCode: 100,
          facilityGroupCode: 60,
          indLogic: false,
          indFee: false,
          voucher: false,
        },
        {
          facilityCode: 220,
          facilityGroupCode: 60,
          indLogic: false,
          voucher: false,
        },
        {
          facilityCode: 250,
          facilityGroupCode: 60,
          indYesOrNo: true,
          voucher: false,
        },
        {
          facilityCode: 298,
          facilityGroupCode: 60,
          indLogic: false,
          number: 1,
          voucher: false,
        },
      ],
      roomStays: [
        {
          stayType: "BED",
          order: "1",
          description: "Bed room",
        },
      ],
      PMSRoomCode: "29369",
    },
    {
      roomCode: "TLN.SU",
      isParentRoom: false,
      minPax: 2,
      maxPax: 7,
      maxAdults: 7,
      maxChildren: 6,
      minAdults: 1,
      roomType: "TLN",
      characteristicCode: "SU",
    },
    {
      roomCode: "TWN.DX",
      isParentRoom: false,
      minPax: 1,
      maxPax: 4,
      maxAdults: 4,
      maxChildren: 3,
      minAdults: 1,
      roomType: "TWN",
      characteristicCode: "DX",
    },
    {
      roomCode: "TWN.DX-PE",
      isParentRoom: false,
      minPax: 1,
      maxPax: 4,
      maxAdults: 4,
      maxChildren: 3,
      minAdults: 1,
      roomType: "TWN",
      characteristicCode: "DX-PE",
    },
    {
      roomCode: "TWN.LX-1",
      isParentRoom: false,
      minPax: 1,
      maxPax: 4,
      maxAdults: 4,
      maxChildren: 3,
      minAdults: 1,
      roomType: "TWN",
      characteristicCode: "LX-1",
    },
    {
      roomCode: "TWN.ST",
      isParentRoom: false,
      minPax: 1,
      maxPax: 4,
      maxAdults: 4,
      maxChildren: 3,
      minAdults: 1,
      roomType: "TWN",
      characteristicCode: "ST",
    },
    {
      roomCode: "TWN.SU",
      isParentRoom: true,
      minPax: 1,
      maxPax: 2,
      maxAdults: 2,
      maxChildren: 1,
      minAdults: 1,
      roomType: "TWN",
      characteristicCode: "SU",
      roomFacilities: [
        {
          facilityCode: 100,
          facilityGroupCode: 60,
          indLogic: false,
          indFee: false,
          voucher: false,
        },
        {
          facilityCode: 220,
          facilityGroupCode: 60,
          indLogic: false,
          number: 0,
          voucher: false,
        },
        {
          facilityCode: 250,
          facilityGroupCode: 60,
          indYesOrNo: true,
          voucher: false,
        },
        {
          facilityCode: 261,
          facilityGroupCode: 60,
          indFee: false,
          indYesOrNo: true,
          voucher: false,
        },
        {
          facilityCode: 295,
          facilityGroupCode: 60,
          number: 28,
          indYesOrNo: true,
          voucher: false,
        },
        {
          facilityCode: 298,
          facilityGroupCode: 60,
          indLogic: false,
          number: 1,
          voucher: false,
        },
      ],
      roomStays: [
        {
          stayType: "BED",
          order: "1",
          description: "Bed room",
          roomStayFacilities: [
            {
              facilityCode: 1,
              facilityGroupCode: 61,
              number: 2,
            },
          ],
        },
      ],
      PMSRoomCode: "5",
    },
    {
      roomCode: "TWN.SU-1",
      isParentRoom: false,
      minPax: 1,
      maxPax: 4,
      maxAdults: 4,
      maxChildren: 3,
      minAdults: 1,
      roomType: "TWN",
      characteristicCode: "SU-1",
    },
    {
      roomCode: "TWN.PI",
      isParentRoom: false,
      minPax: 1,
      maxPax: 4,
      maxAdults: 4,
      maxChildren: 3,
      minAdults: 1,
      roomType: "TWN",
      characteristicCode: "PI",
    },
  ],
  facilities: [
    {
      facilityCode: 20,
      facilityGroupCode: 10,
      order: 1,
      number: 2001,
      voucher: false,
    },
    {
      facilityCode: 70,
      facilityGroupCode: 10,
      order: 1,
      indYesOrNo: true,
      number: 240,
      voucher: false,
    },
    {
      facilityCode: 50,
      facilityGroupCode: 10,
      order: 1,
      number: 24,
      voucher: false,
    },
    {
      facilityCode: 124,
      facilityGroupCode: 10,
      order: 1,
      number: 1,
      voucher: false,
    },
    {
      facilityCode: 10,
      facilityGroupCode: 20,
      order: 1,
      indLogic: true,
      indFee: false,
      voucher: false,
    },
    {
      facilityCode: 10,
      facilityGroupCode: 30,
      order: 1,
      indLogic: true,
      indFee: false,
      voucher: false,
    },
    {
      facilityCode: 40,
      facilityGroupCode: 30,
      order: 1,
      indLogic: true,
      indFee: false,
      voucher: false,
    },
    {
      facilityCode: 50,
      facilityGroupCode: 30,
      order: 1,
      indLogic: true,
      indFee: false,
      voucher: false,
    },
    {
      facilityCode: 60,
      facilityGroupCode: 30,
      order: 1,
      indLogic: true,
      indFee: false,
      voucher: false,
    },
    {
      facilityCode: 260,
      facilityGroupCode: 60,
      order: 1,
      indLogic: false,
      voucher: false,
    },
    {
      facilityCode: 20,
      facilityGroupCode: 60,
      order: 1,
      indLogic: true,
      voucher: false,
    },
    {
      facilityCode: 30,
      facilityGroupCode: 60,
      order: 1,
      indLogic: true,
      voucher: false,
    },
    {
      facilityCode: 40,
      facilityGroupCode: 60,
      order: 1,
      indLogic: true,
      indFee: false,
      voucher: false,
    },
    {
      facilityCode: 280,
      facilityGroupCode: 60,
      order: 1,
      indLogic: true,
      indFee: false,
      voucher: false,
    },
    {
      facilityCode: 281,
      facilityGroupCode: 60,
      order: 1,
      indLogic: true,
      indFee: false,
      voucher: false,
    },
    {
      facilityCode: 304,
      facilityGroupCode: 60,
      order: 1,
      indLogic: true,
      indFee: false,
      voucher: false,
    },
    {
      facilityCode: 55,
      facilityGroupCode: 60,
      order: 1,
      indLogic: true,
      indFee: false,
      voucher: false,
    },
    {
      facilityCode: 289,
      facilityGroupCode: 60,
      order: 1,
      indLogic: true,
      indFee: false,
      voucher: false,
    },
    {
      facilityCode: 120,
      facilityGroupCode: 60,
      order: 1,
      indLogic: true,
      indFee: false,
      voucher: false,
    },
    {
      facilityCode: 200,
      facilityGroupCode: 60,
      order: 1,
      indLogic: true,
      indFee: false,
      voucher: false,
    },
    {
      facilityCode: 287,
      facilityGroupCode: 60,
      order: 1,
      indYesOrNo: false,
      voucher: false,
    },
    {
      facilityCode: 275,
      facilityGroupCode: 60,
      order: 1,
      indLogic: false,
      indFee: false,
      voucher: false,
    },
    {
      facilityCode: 264,
      facilityGroupCode: 60,
      order: 1,
      indLogic: false,
      indFee: false,
      voucher: false,
    },
    {
      facilityCode: 295,
      facilityGroupCode: 70,
      order: 1,
      indYesOrNo: false,
      voucher: false,
    },
    {
      facilityCode: 320,
      facilityGroupCode: 70,
      order: 1,
      indFee: true,
      indYesOrNo: true,
      amount: 38,
      currency: "BRL",
      applicationType: "UN",
      voucher: true,
    },
    {
      facilityCode: 30,
      facilityGroupCode: 70,
      order: 1,
      indYesOrNo: true,
      voucher: false,
    },
    {
      facilityCode: 260,
      facilityGroupCode: 70,
      order: 1,
      timeFrom: "14:00:00",
      timeTo: "00:00:00",
      voucher: true,
    },
    {
      facilityCode: 390,
      facilityGroupCode: 70,
      order: 1,
      timeTo: "12:00:00",
      voucher: false,
    },
    {
      facilityCode: 240,
      facilityGroupCode: 70,
      order: 1,
      indLogic: true,
      indFee: false,
      voucher: false,
    },
    {
      facilityCode: 250,
      facilityGroupCode: 70,
      order: 1,
      indLogic: false,
      indFee: true,
      voucher: false,
    },
    {
      facilityCode: 550,
      facilityGroupCode: 70,
      order: 1,
      indFee: false,
      indYesOrNo: true,
      voucher: false,
    },
    {
      facilityCode: 270,
      facilityGroupCode: 70,
      order: 1,
      indLogic: true,
      indFee: false,
      voucher: false,
    },
    {
      facilityCode: 280,
      facilityGroupCode: 70,
      order: 1,
      indLogic: true,
      indFee: true,
      voucher: false,
    },
    {
      facilityCode: 505,
      facilityGroupCode: 70,
      order: 1,
      indLogic: true,
      indFee: false,
      voucher: false,
    },
    {
      facilityCode: 10,
      facilityGroupCode: 70,
      order: 1,
      indLogic: true,
      voucher: false,
    },
    {
      facilityCode: 40,
      facilityGroupCode: 70,
      order: 1,
      indLogic: true,
      indFee: false,
      voucher: false,
    },
    {
      facilityCode: 70,
      facilityGroupCode: 70,
      order: 1,
      indLogic: true,
      indFee: false,
      voucher: false,
    },
    {
      facilityCode: 585,
      facilityGroupCode: 70,
      order: 1,
      indLogic: true,
      indFee: false,
      voucher: false,
    },
    {
      facilityCode: 470,
      facilityGroupCode: 70,
      order: 1,
      indLogic: true,
      indFee: false,
      voucher: false,
    },
    {
      facilityCode: 559,
      facilityGroupCode: 70,
      order: 1,
      indLogic: true,
      indFee: false,
      voucher: false,
    },
    {
      facilityCode: 578,
      facilityGroupCode: 70,
      order: 1,
      indLogic: true,
      indFee: false,
      voucher: false,
    },
    {
      facilityCode: 130,
      facilityGroupCode: 71,
      order: 1,
      indLogic: true,
      indFee: false,
      voucher: false,
    },
    {
      facilityCode: 200,
      facilityGroupCode: 71,
      order: 1,
      indLogic: true,
      voucher: false,
    },
    {
      facilityCode: 220,
      facilityGroupCode: 71,
      order: 1,
      indLogic: true,
      indFee: false,
      voucher: false,
    },
    {
      facilityCode: 575,
      facilityGroupCode: 71,
      order: 1,
      indLogic: true,
      voucher: false,
    },
    {
      facilityCode: 170,
      facilityGroupCode: 72,
      order: 1,
      indLogic: true,
      number: 5,
      voucher: false,
    },
    {
      facilityCode: 575,
      facilityGroupCode: 72,
      order: 1,
      indLogic: true,
      voucher: false,
    },
    {
      facilityCode: 605,
      facilityGroupCode: 72,
      order: 1,
      indLogic: true,
      indFee: false,
      voucher: false,
    },
    {
      facilityCode: 360,
      facilityGroupCode: 73,
      order: 1,
      indFee: false,
      number: 1,
      voucher: false,
    },
    {
      facilityCode: 395,
      facilityGroupCode: 73,
      order: 1,
      indLogic: true,
      indFee: false,
      voucher: false,
    },
    {
      facilityCode: 420,
      facilityGroupCode: 74,
      order: 1,
      indLogic: true,
      indFee: false,
      voucher: false,
    },
    {
      facilityCode: 40,
      facilityGroupCode: 80,
      order: 1,
      indLogic: true,
      timeFrom: "06:00:00",
      timeTo: "10:00:00",
      voucher: false,
    },
    {
      facilityCode: 562,
      facilityGroupCode: 85,
      order: 1,
      indLogic: true,
      indFee: false,
      voucher: false,
    },
    {
      facilityCode: 89,
      facilityGroupCode: 91,
      order: 1,
      indLogic: true,
      dateTo: "2049-12-31",
      voucher: false,
    },
  ],
  terminals: [
    {
      terminalCode: "CGH",
      distance: 9,
    },
    {
      terminalCode: "GRU",
      distance: 28,
    },
  ],
  issues: [
    {
      issueCode: "DECLARATION",
      issueType: "DECLARATION",
      dateFrom: "2015-03-22",
      dateTo: "2040-12-31",
      order: 1,
      alternative: false,
    },
  ],
  interestPoints: [
    {
      facilityCode: 10,
      facilityGroupCode: 100,
      order: 1,
      poiName: "Avenida Paulista  ",
      distance: "20",
    },
    {
      facilityCode: 40,
      facilityGroupCode: 100,
      order: 1,
      poiName: "Centro de Convenções Rebouças ",
      distance: "2000",
    },
    {
      facilityCode: 30,
      facilityGroupCode: 100,
      order: 1,
      poiName: "Centro de Convenções Frei Caneca ",
      distance: "500",
    },
    {
      facilityCode: 20,
      facilityGroupCode: 100,
      order: 1,
      poiName: "Shopping Paulista ",
      distance: "500",
    },
  ],
  images: [
    {
      imageTypeCode: "RES",
      path: "01/019387/019387a_hb_r_009.jpg",
      order: 9,
      visualOrder: 505,
    },
    {
      imageTypeCode: "DEP",
      path: "01/019387/019387a_hb_f_002.jpg",
      order: 2,
      visualOrder: 802,
    },
    {
      imageTypeCode: "RES",
      path: "01/019387/019387a_hb_r_005.jpg",
      order: 5,
      visualOrder: 502,
    },
    {
      imageTypeCode: "DEP",
      path: "01/019387/019387a_hb_f_001.jpg",
      order: 1,
      visualOrder: 801,
    },
    {
      imageTypeCode: "RES",
      path: "01/019387/019387a_hb_r_006.jpg",
      order: 6,
      visualOrder: 503,
    },
    {
      imageTypeCode: "RES",
      path: "01/019387/019387a_hb_r_008.jpg",
      order: 8,
      visualOrder: 501,
    },
    {
      imageTypeCode: "COM",
      path: "01/019387/019387a_hb_l_001.jpg",
      order: 1,
      visualOrder: 101,
    },
    {
      imageTypeCode: "COM",
      path: "01/019387/019387a_hb_l_003.jpg",
      order: 3,
      visualOrder: 105,
    },
    {
      imageTypeCode: "COM",
      path: "01/019387/019387a_hb_l_002.jpg",
      order: 2,
      visualOrder: 104,
    },
    {
      imageTypeCode: "PIS",
      path: "01/019387/019387a_hb_p_002.jpg",
      order: 2,
      visualOrder: 402,
    },
    {
      imageTypeCode: "BAR",
      path: "01/019387/019387a_hb_ba_001.jpg",
      order: 1,
      visualOrder: 602,
    },
    {
      imageTypeCode: "PIS",
      path: "01/019387/019387a_hb_p_001.jpg",
      order: 1,
      visualOrder: 401,
    },
    {
      imageTypeCode: "BAR",
      path: "01/019387/019387a_hb_ba_002.jpg",
      order: 2,
      visualOrder: 601,
    },
    {
      imageTypeCode: "COM",
      path: "01/019387/019387a_hb_l_005.jpg",
      order: 5,
      visualOrder: 102,
    },
    {
      imageTypeCode: "COM",
      path: "01/019387/019387a_hb_l_004.jpg",
      order: 4,
      visualOrder: 106,
    },
    {
      imageTypeCode: "COM",
      path: "01/019387/019387a_hb_l_006.jpg",
      order: 6,
      visualOrder: 103,
    },
    {
      imageTypeCode: "PIS",
      path: "01/019387/019387a_hb_p_004.jpg",
      order: 4,
      visualOrder: 405,
    },
    {
      imageTypeCode: "PIS",
      path: "01/019387/019387a_hb_p_003.jpg",
      order: 3,
      visualOrder: 404,
    },
    {
      imageTypeCode: "PIS",
      path: "01/019387/019387a_hb_p_006.jpg",
      order: 6,
      visualOrder: 406,
    },
    {
      imageTypeCode: "PIS",
      path: "01/019387/019387a_hb_p_007.jpg",
      order: 7,
      visualOrder: 403,
    },
    {
      imageTypeCode: "HAB",
      path: "01/019387/019387a_hb_ro_010.jpg",
      roomCode: "DBL.DX-1",
      roomType: "DBL",
      characteristicCode: "DX-1",
      order: 10,
      visualOrder: 310,
    },
    {
      imageTypeCode: "HAB",
      path: "01/019387/019387a_hb_ro_001.jpg",
      roomCode: "SGL.PE",
      roomType: "SGL",
      characteristicCode: "PE",
      order: 1,
      visualOrder: 317,
    },
    {
      imageTypeCode: "HAB",
      path: "01/019387/019387a_hb_ro_006.jpg",
      roomCode: "DBL.DX",
      roomType: "DBL",
      characteristicCode: "DX",
      order: 6,
      visualOrder: 312,
    },
    {
      imageTypeCode: "HAB",
      path: "01/019387/019387a_hb_ro_005.jpg",
      roomCode: "SGL.LX",
      roomType: "SGL",
      characteristicCode: "LX",
      order: 5,
      visualOrder: 314,
    },
    {
      imageTypeCode: "HAB",
      path: "01/019387/019387a_hb_ro_020.jpg",
      roomCode: "TWN.SU",
      roomType: "TWN",
      characteristicCode: "SU",
      order: 20,
      visualOrder: 321,
    },
    {
      imageTypeCode: "HAB",
      path: "01/019387/019387a_hb_ro_027.jpg",
      roomCode: "SGL.PE",
      roomType: "SGL",
      characteristicCode: "PE",
      order: 27,
      visualOrder: 304,
    },
    {
      imageTypeCode: "HAB",
      path: "01/019387/019387a_hb_ro_029.jpg",
      roomCode: "DBL.PE",
      roomType: "DBL",
      characteristicCode: "PE",
      order: 29,
      visualOrder: 305,
    },
    {
      imageTypeCode: "HAB",
      path: "01/019387/019387a_hb_ro_031.jpg",
      roomCode: "SGL.PE",
      roomType: "SGL",
      characteristicCode: "PE",
      order: 32,
      visualOrder: 306,
    },
    {
      imageTypeCode: "GEN",
      path: "01/019387/019387a_hb_a_008.jpg",
      order: 8,
      visualOrder: 11,
    },
    {
      imageTypeCode: "CON",
      path: "01/019387/019387a_hb_k_002.jpg",
      order: 2,
      visualOrder: 703,
    },
    {
      imageTypeCode: "GEN",
      path: "01/019387/019387a_hb_a_007.jpg",
      order: 7,
      visualOrder: 10,
    },
    {
      imageTypeCode: "CON",
      path: "01/019387/019387a_hb_k_001.jpg",
      order: 1,
      visualOrder: 702,
    },
    {
      imageTypeCode: "HAB",
      path: "01/019387/019387a_hb_ro_035.jpg",
      roomCode: "DBL.DB-SU",
      roomType: "DBL",
      characteristicCode: "DB-SU",
      order: 35,
      visualOrder: 308,
    },
    {
      imageTypeCode: "GEN",
      path: "01/019387/019387a_hb_a_009.jpg",
      order: 9,
      visualOrder: 9,
    },
    {
      imageTypeCode: "HAB",
      path: "01/019387/019387a_hb_ro_009.jpg",
      roomCode: "SGL.DX-1",
      roomType: "SGL",
      characteristicCode: "DX-1",
      order: 9,
      visualOrder: 315,
    },
    {
      imageTypeCode: "HAB",
      path: "01/019387/019387a_hb_ro_027.jpg",
      roomCode: "SGL.PE",
      roomType: "SGL",
      characteristicCode: "PE",
      order: 28,
      visualOrder: 304,
    },
    {
      imageTypeCode: "HAB",
      path: "01/019387/019387a_hb_ro_029.jpg",
      roomCode: "DBL.PE",
      roomType: "DBL",
      characteristicCode: "PE",
      order: 30,
      visualOrder: 305,
    },
    {
      imageTypeCode: "HAB",
      path: "01/019387/019387a_hb_ro_008.jpg",
      roomCode: "DBL.DX-SU",
      roomType: "DBL",
      characteristicCode: "DX-SU",
      order: 8,
      visualOrder: 311,
    },
    {
      imageTypeCode: "CON",
      path: "01/019387/019387a_hb_k_004.jpg",
      order: 4,
      visualOrder: 701,
    },
    {
      imageTypeCode: "CON",
      path: "01/019387/019387a_hb_k_003.jpg",
      order: 3,
      visualOrder: 701,
    },
    {
      imageTypeCode: "HAB",
      path: "01/019387/019387a_hb_ro_018.jpg",
      roomCode: "SGL.SU",
      roomType: "SGL",
      characteristicCode: "SU",
      order: 18,
      visualOrder: 318,
    },
    {
      imageTypeCode: "HAB",
      path: "01/019387/019387a_hb_ro_007.jpg",
      roomCode: "SGL.DX",
      roomType: "SGL",
      characteristicCode: "DX",
      order: 7,
      visualOrder: 316,
    },
    {
      imageTypeCode: "HAB",
      path: "01/019387/019387a_hb_ro_004.jpg",
      roomCode: "DBL.LX",
      roomType: "DBL",
      characteristicCode: "LX",
      order: 4,
      visualOrder: 309,
    },
    {
      imageTypeCode: "RES",
      path: "01/019387/019387a_hb_r_010.jpg",
      order: 10,
      visualOrder: 506,
    },
    {
      imageTypeCode: "RES",
      path: "01/019387/019387a_hb_r_011.jpg",
      order: 11,
      visualOrder: 507,
    },
    {
      imageTypeCode: "HAB",
      path: "01/019387/019387a_hb_ro_033.jpg",
      roomCode: "SGL.PE",
      roomType: "SGL",
      characteristicCode: "PE",
      order: 33,
      visualOrder: 307,
    },
    {
      imageTypeCode: "RES",
      path: "01/019387/019387a_hb_r_012.jpg",
      order: 12,
      visualOrder: 508,
    },
    {
      imageTypeCode: "RES",
      path: "01/019387/019387a_hb_r_013.jpg",
      order: 13,
      visualOrder: 509,
    },
    {
      imageTypeCode: "HAB",
      path: "01/019387/019387a_hb_ro_031.jpg",
      roomCode: "SGL.PE",
      roomType: "SGL",
      characteristicCode: "PE",
      order: 31,
      visualOrder: 306,
    },
    {
      imageTypeCode: "RES",
      path: "01/019387/019387a_hb_r_014.jpg",
      order: 14,
      visualOrder: 504,
    },
    {
      imageTypeCode: "HAB",
      path: "01/019387/019387a_hb_ro_023.jpg",
      roomCode: "DBL.PE",
      roomType: "DBL",
      characteristicCode: "PE",
      order: 24,
      visualOrder: 302,
    },
    {
      imageTypeCode: "HAB",
      path: "01/019387/019387a_hb_ro_033.jpg",
      roomCode: "SGL.PE",
      roomType: "SGL",
      characteristicCode: "PE",
      order: 34,
      visualOrder: 307,
    },
    {
      imageTypeCode: "HAB",
      path: "01/019387/019387a_hb_ro_012.jpg",
      roomCode: "DBL.SU",
      roomType: "DBL",
      characteristicCode: "SU",
      order: 12,
      visualOrder: 313,
    },
    {
      imageTypeCode: "HAB",
      path: "01/019387/019387a_hb_ro_023.jpg",
      roomCode: "DBL.PE",
      roomType: "DBL",
      characteristicCode: "PE",
      order: 23,
      visualOrder: 302,
    },
  ],
  wildcards: [
    {
      roomType: "SGL.2B-2",
      roomCode: "SGL",
      characteristicCode: "2B-2",
      hotelRoomDescription: {
        content: "Single Two Beds Capacity 01",
      },
    },
    {
      roomType: "SGL.PE",
      roomCode: "SGL",
      characteristicCode: "PE",
      hotelRoomDescription: {
        content: "Luxury Premier Double Bed Capacity 01",
      },
    },
    {
      roomType: "SGL.2B-1",
      roomCode: "SGL",
      characteristicCode: "2B-1",
      hotelRoomDescription: {
        content: "Single Two Beds",
      },
    },
    {
      roomType: "DBL.LX",
      roomCode: "DBL",
      characteristicCode: "LX",
      hotelRoomDescription: {
        content: "Luxury Double Bed",
      },
    },
    {
      roomType: "SGL.SU",
      roomCode: "SGL",
      characteristicCode: "SU",
      hotelRoomDescription: {
        content: "Superior Double Bed Capacity 01",
      },
    },
    {
      roomType: "DBL.DB-SU",
      roomCode: "DBL",
      characteristicCode: "DB-SU",
      hotelRoomDescription: {
        content: "Double Superior with Double Bed",
      },
    },
    {
      roomType: "DBL.SU",
      roomCode: "DBL",
      characteristicCode: "SU",
      hotelRoomDescription: {
        content: "Superior Double Bed",
      },
    },
    {
      roomType: "SGL.DX-1",
      roomCode: "SGL",
      characteristicCode: "DX-1",
      hotelRoomDescription: {
        content: "DELUXE SUPERIOR",
      },
    },
    {
      roomType: "TWN.SU",
      roomCode: "TWN",
      characteristicCode: "SU",
      hotelRoomDescription: {
        content: "Superior Two Beds",
      },
    },
    {
      roomType: "DBL.PE",
      roomCode: "DBL",
      characteristicCode: "PE",
      hotelRoomDescription: {
        content: "Luxury Premier Double Bed",
      },
    },
    {
      roomType: "DBL.DX-1",
      roomCode: "DBL",
      characteristicCode: "DX-1",
      hotelRoomDescription: {
        content: "DELUXE SUPERIOR",
      },
    },
    {
      roomType: "SGL.LX",
      roomCode: "SGL",
      characteristicCode: "LX",
      hotelRoomDescription: {
        content: "Luxury Double Bed Capacity 01",
      },
    },
  ],
  web: "www.bluetree.com.br",
  lastUpdate: "2024-11-01",
  S2C: "2*",
  ranking: 27,
};

const hotel = {
  hotels: [
    {
      S2C: "4*",
      accommodationType: {
        code: "HOTEL",
        typeDescription: "Hotel",
        typeMultiDescription: {
          content: "string",
          languageCode: "string",
        },
      },
      accommodationTypeCode: "HOTEL",
      address: {
        content: "string",
        languageCode: "string",
      },
      boardCodes: ["BB"],
      boards: [
        {
          code: "AI",
          description: {
            content: "string",
            languageCode: "string",
          },
          multiLingualCode: "AI",
        },
      ],
      category: {
        accommodationType: "HOTEL",
        code: "4EST",
        description: {
          content: "string",
          languageCode: "string",
        },
        group: "GRUPO4",
        simpleCode: 0,
      },
      categoryCode: "4EST",
      categoryGroup: {
        code: "GRUPO4",
        description: {
          content: "string",
          languageCode: "string",
        },
        name: {
          content: "string",
          languageCode: "string",
        },
        order: 0,
      },
      categoryGroupCode: "GRUPO4",
      chain: {
        code: 7,
        description: {
          content: "string",
          languageCode: "string",
        },
      },
      chainCode: "S.HOT",
      city: {
        content: "string",
        languageCode: "string",
      },
      code: 0,
      coordinates: {
        latitude: 39.5554,
        longitude: 2.62155,
      },
      country: {
        code: "PT",
        description: {
          content: "string",
          languageCode: "string",
        },
        isoCode: "PT",
        states: [
          {
            code: "CA",
            name: "CALIFORNIA",
          },
        ],
      },
      countryCode: "PT",
      description: {
        content: "string",
        languageCode: "string",
      },
      destination: {
        code: "PMI",
        countryCode: "ES",
        groupZones: [
          {
            groupZoneCode: "MALLOPMI16",
            name: {
              content: "string",
              languageCode: "string",
            },
            zones: [0],
          },
        ],
        isoCode: "ES",
        name: {
          content: "string",
          languageCode: "string",
        },
        zones: [
          {
            description: {
              content: "string",
              languageCode: "string",
            },
            name: "Candabong",
            zoneCode: 0,
          },
        ],
      },
      destinationCode: "FAO",
      email: "geral@aqualuzlagos.pt",
      exclusiveDeal: 0,
      facilities: [
        {
          ageFrom: 0,
          ageTo: 0,
          amount: 0,
          applicationType: "UN",
          currency: "EUR",
          dateFrom: "2020-06-01",
          dateTo: "2021-06-01",
          description: {
            content: "string",
            languageCode: "string",
          },
          distance: 0,
          facilityCode: 0,
          facilityGroupCode: 0,
          facilityName: "Bar",
          indFee: true,
          indLogic: true,
          indYesOrNo: true,
          number: 0,
          order: 0,
          timeFrom: "14:00:00",
          timeTo: "00:00:00",
          voucher: true,
        },
      ],
      giataCode: 0,
      images: [
        {
          characteristicCode: "B2-PI",
          imageTypeCode: "RES",
          order: 0,
          path: "00/000112/000112a_hb_ro_025.jpg",
          roomCode: "APT.B2-PI",
          roomType: "APT",
          type: {
            code: "HAB",
            description: {
              content: "string",
              languageCode: "string",
            },
          },
          visualOrder: 0,
          PMSRoomCode: "K1CN",
        },
      ],
      interestPoints: [
        {
          distance: 3000,
          facilityCode: 0,
          facilityGroupCode: 0,
          fee: true,
          order: 0,
          poiName: "Port Aventura",
        },
      ],
      issues: [
        {
          alternative: true,
          dateFrom: "2020-07-20",
          dateTo: "2020-07-26",
          description: {
            content: "string",
            languageCode: "string",
          },
          issueCode: "SPA",
          issueType: "REFURBISHMENT",
          order: 0,
        },
      ],
      lastUpdate: "2020-02-08",
      license: 4470,
      name: {
        content: "string",
        languageCode: "string",
      },
      phones: [
        {
          phoneNumber: 34902400661,
          phoneType: "PHONEBOOKING",
        },
      ],
      postalCode: 4740,
      ranking: 0,
      rooms: [
        {
          characteristicCode: "ST",
          description: "DOUBLE STANDARD",
          roomCode: "DBL.ST",
          roomFacilities: [
            {
              description: {
                content: "string",
                languageCode: "string",
              },
              facilityCode: 0,
              facilityGroupCode: 0,
              indFee: true,
              indLogic: true,
              indYesOrNo: true,
              number: 0,
              order: 0,
              voucher: true,
            },
          ],
          roomStays: [
            {
              description: "Bed room",
              order: 1,
              roomStayFacilities: [
                {
                  description: {},
                  facilityCode: 1,
                  facilityGroupCode: 61,
                  number: 2,
                },
              ],
              stayType: "BED",
            },
          ],
          roomType: "DBL",
        },
      ],
      segmentCodes: [0],
      segments: [
        {
          code: 0,
          description: {
            content: "string",
            languageCode: "string",
          },
        },
      ],
      state: {
        code: "CA",
        name: "CALIFORNIA",
      },
      stateCode: "AL",
      terminals: [
        {
          description: {
            content: "string",
            languageCode: "string",
          },
          distance: 0,
          name: {
            content: "string",
            languageCode: "string",
          },
          terminalCode: "FAO",
          terminalType: "A",
        },
      ],
      web: "www.aqualuz.com",
      wildcards: [
        {
          characteristicCode: "ST-2",
          hotelRoomDescription: {
            content: "string",
            languageCode: "string",
          },
          roomCode: "DBT",
          roomType: "DBT.ST-2",
        },
      ],
      zone: {
        description: {
          content: "string",
          languageCode: "string",
        },
        name: "Candabong",
        zoneCode: 0,
      },
      zoneCode: 0,
    },
  ],
};
